<a href="https://colab.research.google.com/github/Sumant25/My_repository/blob/main/Python_Practise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Why we should use Numpy array when we have Python list??**

Numpy array are:

1.   FAST
2.   CONVENIENCE
3.   USES LESS MEMEORY
4.   FUNCTIONALITY



***Memory Consumption Test of Numpy Array vs Python List***

In [3]:
import time
import sys

In [9]:
b= range(1000) # creating a list of 1000 numbers from 0 to 999.
print('total memory occupied by 1000 elements in Python list:')
print(sys.getsizeof(5)*len(b), "bytes")

total memory occupied by 1000 elements in Python :
28000 bytes


In [11]:
c = np.arange(1000) # creating an array of 1000 nos.
print('total memory occupied by 1000 elements in Numpy array:')
print((c.itemsize * c.size),'bytes')

total memory occupied by 1000 elements in Numpy array:
8000 bytes


***Comparing the Speed of Numpy array vs Python List***

In [14]:
# How much it takes to add 1 million elements in LIST vs ARRAY

size = 1000000

A1 = range(size)
A2 = range(size)

start = time.time() # capture start-time before processing
result = [x+y for x,y in zip(A1,A2)]
stop = time.time() # capture stop-time after processing
# (stop-start)*1000 # to convert the time-diff into milliseconds
print('time taken by python list addition -> ', (stop-start)*1000, ' ms') 

L1 = np.arange(size)
L2 = np.arange(size)

start = time.time()
result = L1 + L2
stop = time.time()
print('time taken by numpy array addition -> ', (stop-start)*1000, ' ms')

time taken by python list addition ->  131.78277015686035  ms
time taken by numpy array addition ->  18.596649169921875  ms


In [40]:
# 1-D array
arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [41]:
arr1.tolist()

[10, 20, 30, 40, 50]

In [26]:
# 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# alternatively using 2-D list
mylist = [[1,2,3],[4,5,6]]
b = np.array(mylist)
print(b)

[[1 2 3]
 [4 5 6]]


In [31]:
# 3-D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**Checking dimensions & Shape of an Array**

In [32]:
arr3.ndim

3

In [33]:
arr3.shape

(2, 2, 3)

In [29]:
b.ndim  # To check no of dimensions

2

In [30]:
b.shape # it gives no of Rows X no. of Columns

(2, 3)

**Indexing in Numpy Array**

In [34]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3[-1][-1][-1]

12

In [44]:
arr3[1][1][2]

12

In [56]:
arr3[1,1,2]

12

In [58]:
a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
b = a[:2,1:3]   # :2 -> means all rows till (2-1) rows from end , 1:3 means -> covering columns from index 1 to last-1
b

array([[2, 3],
       [6, 7]])

In [70]:
a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]], dtype='float')
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [63]:
a[[0,1]]

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [64]:
a.max()

12.0

In [66]:
a.min()

1.0

**BASIC NUMPY OPERATIONS**

In [78]:
np.ones((22,1,2,3), dtype=np.int_)

array([[[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]]])

In [79]:
len(arr3)

2